export const ActionTypes = {
  // info
  SET_OPTIONS: "SET_OPTIONS",
  SET_RATE: "SET_RATE",

  // from name
  SET_FROM_NAME: "SET_FROM_NAME",
  SET_FROM_AMOUNT: "SET_FROM_AMOUNT",
  SET_FROM_LONGNAME: "SET_FROM_LONGNAME",
  SET_FROM_SYMBOL: "SET_FROM_SYMBOL",
  SET_FROM_FLAGS: "SET_FROM_FLAGS",

  // to name
  SET_TO_NAME: "SET_TO_NAME",
  SET_TO_AMOUNT: "SET_TO_AMOUNT",
  SET_TO_LONGNAME: "SET_TO_LONGNAME",
  SET_TO_SYMBOL: "SET_TO_SYMBOL",
  SET_TO_FLAGS: "SET_TO_FLAGS",

  // header
  SET_HEADER_USD: "SET_HEADER_USD",
  SET_HEADER_EUR: "SET_HEADER_EUR",
};
